=== yousra-tech/ITI-XML/Lab1a.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT family (grandfather)>
<!ELEMENT grandfather (#PCDATA|father|uncle|aunt)*>
<!ELEMENT father (#PCDATA|mother|daughter|son)*>
<!ELEMENT mother (#PCDATA)>
<!ELEMENT daughter (#PCDATA)>
<!ELEMENT son (#PCDATA)>
<!ELEMENT uncle (#PCDATA)>
<!ELEMENT aunt (#PCDATA)>

<!ATTLIST father job (engineer | Accountant | doctor) "engineer">
<!ATTLIST daughter job (engineer | Accountant | doctor) "engineer">
<!ATTLIST daughter age NMTOKEN #REQUIRED>
<!ATTLIST son age NMTOKEN #REQUIRED>
<!ATTLIST son sport (tennis | football) "football">
<!ATTLIST aunt sons (jana | belal | remas) "belal">

=== yousra-tech/ITI-XML/Lab1a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "D:\yousra\iti\xml\day1\Lab\MyAssignment\Lab1a.dtd">
<family>
	<grandfather>elsayed
		<father job="engineer">zaki
			<mother>zainab
			</mother>
			<daughter age="20" job="engineer">radwa
			</daughter>
			<son age="25" sport="football">adam
			</son>
		</father>
		<uncle>ahmed
		</uncle>
		<uncle>mohamed
		</uncle>
		<aunt sons="belal">marwa
		</aunt>
	</grandfather>
</family>
