=== yousra-tech/ITI-XML/Untitled10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">  
 <xs:simpleType name="test1">
		<xs:restriction base="xs:string">
		  <xs:enumeration value="football"/>
		  <xs:enumeration value="volleyball"/>
		  <xs:enumeration value="basketball"/>
		</xs:restriction>
	</xs:simpleType>
  <xs:simpleType name="test2">
			<xs:restriction base="xs:integer">
			  <xs:minInclusive value="10"/>
			  <xs:maxInclusive value="25"/>
			
			</xs:restriction>
		
		</xs:simpleType>
 
	<xs:element name="family">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="grandfather">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="father" maxOccurs="2">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="mother">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="job" type="xs:string" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="daughter" minOccurs="1" maxOccurs="2">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="age" type="xs:integer"/>
														<xs:attribute name="sport" type="test1"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="son" minOccurs="1" maxOccurs="2">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="age" type="test2"/>
														<xs:attribute name="sport" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="uncle" type="xs:string" maxOccurs="3"/>
							<xs:element name="aunt">
								<xs:complexType>
									<xs:attribute name="job" type="xs:string" fixed="doctor"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="loc" type="xs:string" fixed="cairo"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yousra-tech/ITI-XML/Untitled10.xml
<?xml version="1.0" encoding="UTF-8"?>
<family loc="cairo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\nermeen.amin\Desktop\Powe BI Cairo Univ\day 2\Untitled10.xsd">abc
<grandfather> ali <!--fgfg-->
   <father>ahmed
        <mother job="engineer">sara</mother>
			<daughter age="22" sport="football">hoda</daughter>
			<daughter age="23" sport="football">ola</daughter>
			<son age="20" sport="football">ahmed</son>
		</father>
		<father>moh
        <mother job="engineer">sara</mother>
			<daughter age="22" sport="football">hoda</daughter>
			<son age="18" sport="football">ahmed</son>
			<son age="15" sport="football">ahmed</son>
		</father>
		<uncle>moh</uncle>
		<uncle>ahmed</uncle>
		<uncle>ali</uncle>
		<aunt job="doctor"/>
	</grandfather>
</family>
